"""Storage interface for the control plane.

Services depend only on this Protocol, so the same business logic runs on PostgreSQL in
production (`postgres.py`) and in memory in tests (`memory.py`). Every method is a single
atomic operation; `transaction()` groups several into one.
"""

from __future__ import annotations

from contextlib import AbstractAsyncContextManager
from datetime import datetime
from typing import Protocol

from ..domain.records import (
    ActionRecord,
    AdminKeyRecord,
    AgentRecord,
    ApiKeyRecord,
    AssignmentRecord,
    CatalogRecord,
    ChangeRecord,
    GatewayRecord,
    GuardrailVersionRecord,
    ModifierRecord,
    PublishRequestRecord,
    ReviewRecord,
    SnapshotRecord,
    TenantRecord,
)


class Conflict(Exception):
    """Unique constraint or state conflict."""


class Store(Protocol):
    def transaction(self) -> AbstractAsyncContextManager[None]: ...

    # tenants
    async def get_tenant(self, tenant_id: str) -> TenantRecord | None: ...
    async def list_tenants(self) -> list[TenantRecord]: ...
    async def put_tenant(self, tenant: TenantRecord) -> None: ...

    # gateway API keys
    async def add_api_key(self, key: ApiKeyRecord) -> None: ...
    async def get_api_key(self, key_id: str) -> ApiKeyRecord | None: ...
    async def list_api_keys(self, tenant_id: str | None = None) -> list[ApiKeyRecord]: ...
    async def put_api_key(self, key: ApiKeyRecord) -> None: ...

    # agents / actions / modifiers
    async def put_agent(self, agent: AgentRecord) -> None: ...
    async def get_agent(self, tenant_id: str, agent_id: str) -> AgentRecord | None: ...
    async def list_agents(self, tenant_id: str | None = None) -> list[AgentRecord]: ...
    async def delete_agent(self, tenant_id: str, agent_id: str) -> bool: ...
    async def put_action(self, action: ActionRecord) -> ActionRecord: ...
    async def list_actions(self, tenant_id: str | None = None) -> list[ActionRecord]: ...
    async def delete_action(self, tenant_id: str, action_id: str) -> bool: ...
    async def put_modifier(self, modifier: ModifierRecord) -> ModifierRecord: ...
    async def list_modifiers(self, tenant_id: str | None = None) -> list[ModifierRecord]: ...
    async def delete_modifier(self, tenant_id: str, modifier_id: str) -> bool: ...

    # guardrail registry
    async def put_version(self, version: GuardrailVersionRecord) -> None: ...
    async def get_version(self, guardrail_id: str, version: str) -> GuardrailVersionRecord | None: ...
    async def list_versions(self, guardrail_id: str | None = None) -> list[GuardrailVersionRecord]: ...

    # working-set assignments
    async def put_assignment(self, record: AssignmentRecord) -> None: ...
    async def get_assignment(self, environment: str, assignment_id: str) -> AssignmentRecord | None: ...
    async def list_assignments(self, environment: str) -> list[AssignmentRecord]: ...
    async def delete_assignment(self, environment: str, assignment_id: str) -> bool: ...
    async def replace_assignments(self, environment: str, records: list[AssignmentRecord]) -> None: ...

    # snapshots
    async def add_snapshot(self, snapshot: SnapshotRecord) -> None: ...
    async def get_snapshot(self, environment: str, version: str) -> SnapshotRecord | None: ...
    async def current_snapshot(self, environment: str) -> SnapshotRecord | None: ...
    async def set_current_snapshot(self, environment: str, snapshot_id: str) -> None: ...
    async def list_snapshots(self, environment: str, limit: int = 50) -> list[SnapshotRecord]: ...
    async def count_snapshots(self, environment: str) -> int: ...

    # catalog
    async def add_catalog(self, catalog: CatalogRecord) -> None: ...
    async def current_catalog(self) -> CatalogRecord | None: ...

    # publish requests (two-person rule)
    async def add_publish_request(self, request: PublishRequestRecord) -> None: ...
    async def get_publish_request(self, request_id: str) -> PublishRequestRecord | None: ...
    async def put_publish_request(self, request: PublishRequestRecord) -> None: ...
    async def list_publish_requests(
        self, environment: str | None = None, status: str | None = None
    ) -> list[PublishRequestRecord]: ...

    # review queue
    async def add_review(self, review: ReviewRecord) -> None: ...
    async def get_review(self, review_id: str) -> ReviewRecord | None: ...
    async def put_review(self, review: ReviewRecord) -> None: ...
    async def decide_review(
        self, review_id: str, *, status: str, reviewer: str, decided_at: datetime, decision_note: str
    ) -> bool:
        """Atomically decide a review that is still pending and not expired at `decided_at`.

        False if it was decided or expired in the meantime (nothing is overwritten)."""
        ...

    async def add_review_raw_viewer(self, review_id: str, actor: str) -> None:
        """Atomically append to raw_viewed_by (never rewrites the rest of the review)."""
        ...

    async def list_reviews(
        self, tenant_id: str | None = None, status: str | None = None, limit: int = 100
    ) -> list[ReviewRecord]: ...

    # admin keys
    async def add_admin_key(self, key: AdminKeyRecord) -> None: ...
    async def find_admin_key(self, key_hash: str) -> AdminKeyRecord | None: ...
    async def list_admin_keys(self) -> list[AdminKeyRecord]: ...
    async def put_admin_key(self, key: AdminKeyRecord) -> None: ...

    # gateway fleet
    async def put_gateway(self, gateway: GatewayRecord) -> None: ...
    async def list_gateways(self, environment: str | None = None) -> list[GatewayRecord]: ...

    # change log (append-only)
    async def log_change(self, change: ChangeRecord) -> None: ...
    async def list_changes(
        self, entity: str | None = None, entity_id: str | None = None, limit: int = 100
    ) -> list[ChangeRecord]: ...
