ALLOWED_ENTITIES = [
    "AU_ABN", "LOCATION", "MEDICAL_LICENSE", "IN_VOTER", "CRYPTO",
    "PHONE_NUMBER", "IN_VEHICLE_REGISTRATION", "US_DRIVER_LICENSE", "US_PASSPORT",
    "AU_MEDICARE", "US_SSN", "IN_PAN", "IP_ADDRESS", "US_ITIN", "AU_ACN",
    "CREDIT_CARD", "UK_NINO", "IBAN_CODE", "UK_NHS", "DATE_TIME",
    "SG_NRIC_FIN", "NRP", "URL", "AU_TFN", "IN_AADHAAR", "EMAIL_ADDRESS",
    "IN_PASSPORT", "PERSON", "US_BANK_NUMBER"
]
